version: "3.7"

networks:
  techtest_network: {}

services:
  mysql:
    environment:
      - MYSQL_DATABASE=techtest_db
      - MYSQL_PASSWORD=db_password
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_USER=db_user
    image: mysql:latest
    networks:
      - techtest_network
    restart: always
  techtest_service:
    # image: emivespa/techtest:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npx prisma db push && npm run start"
    depends_on:
      - mysql
    env_file:
      - .env
    networks:
      - techtest_network
    ports:
      - "3000:3000"
    restart: always
